http:
  routers:
    keycloak-router:
      rule: "Host(`keycloak.local`)"
      entryPoints:
        - web
        - websecure
      service: keycloak-service
      priority: 10
      tls: {}
    auth-router:
      rule: "Host(`auth.local`)"
      entryPoints:
        - web
        - websecure
      service: auth-service
      priority: 10
      tls: {}
  services:
    keycloak-service:
      loadBalancer:
        servers:
          - url: "http://keycloak-keycloak:8080"
    auth-service:
      loadBalancer:
        servers:
          - url: "http://gogotex-auth:8081"

tls:
  certificates:
    - certFile: /etc/traefik/ssl/octopode.neuro.uni-bremen.de.crt
      keyFile: /etc/traefik/ssl/octopode.neuro.uni-bremen.de.key